### ISSUE TITLE
Remove deprecated field in payload.

### ISSUE THREAD

**Issue by argonlaser** [kgryte/github-create-issue#1]
Thanks for the awesome library. I am using it in one of my projects.

 Github has deprecated the assignee field and gave assignees field instead. Please refer [this](https://developer.github.com/v3/issues/#create-an-issue) for the API doc.

I would be happy to raise a PR for fixing this. Let me know your thoughts on this.

**Comment by kgryte** [comment]
@argonlaser Thanks for reporting the issue. And yes, I am open to a PR to fix this. :)

**Comment by argonlaser** [comment]
Thanks a lot for the reply @kgryte . I am working on it. Could it be 2.0.0 by removing the deprecated field or could it stay backward compatible? (i.e. either of assignee or assignees can be given).

**Comment by kgryte** [comment]
@argonlaser Let's go with the breaking change; i.e., remove support for `assignee` and replace with `assignees`. When the PR is merged, I will published the package as `2.0.0`.

**Comment by argonlaser** [comment]
Addressed in PR https://github.com/kgryte/github-create-issue/pull/2 . Please review and merge.

**Comment by kgryte** [comment]
Closed via #2.

**Comment by kgryte** [comment]
@argonlaser New major published. Thanks again for all your work!

**Comment by argonlaser** [comment]
@kgryte : Thanks a lot for merging.
