### ISSUE TITLE
Can you add the ability to pass a github URL to support GHE?

### ISSUE THREAD

**Issue by scottdickerson** [kgryte/github-create-issue#3]
Currently this only seems to support github.com, can you add an ability to support Github Enterprise allowing the passing of the URL?

**Comment by kgryte** [comment]
I'll take a PR. :) Should be relatively straightforward: add a `url` option, which serves as the base URL to which a `slug` is appended. Add a `--url url` flag to the CLI.

**Comment by kgryte** [comment]
Actually, a new option is not necessary. Currently in `defaults.json`, there is a `hostname` option. I believe this need only be made publicly accessible via `options` and the CLI.

**Comment by kgryte** [comment]
The `pathname` option would, presumably, also need to be made accessible via `options` and the CLI.

**Comment by kgryte** [comment]
Development has moved to [`stdlib`](https://github.com/stdlib-js/stdlib/tree/dc9af9f74c32de9ad16be2cdd0bc0cde42f6f8e7/lib/node_modules/%40stdlib/_tools/github/create-issue). This request was addressed there.
